### ISSUE TITLE
Feature request: Nostr Wallet Connect

### ISSUE THREAD

**Issue by DireMunchkin** [gandlafbtc/nutstash-wallet#100]
**Is your feature request related to a problem? Please describe.**
NWC support would make sending zaps a lot snappier in clients - I.E you get one-tap zaps in Primal, Amethyst and so forth.

**Describe the solution you'd like**
Support for NWC connection strings, and maybe also budgets.

**Describe alternatives you've considered**
I'm currently using Cashu.me as a zapping wallet because it has NWC, but I have some other issues with it.

**Comment by gandlafbtc** [comment]
we'll be adding nwc in the new release of nutstash

you can follow the development here #102
