### ISSUE TITLE
Improve loading speed 

### ISSUE THREAD

**Issue by gandlafbtc** [gandlafbtc/nutstash-wallet#33]
First time page load takes too long because the nutstash logo filesize is too big. 

### Tasks
* [ ] create png with transparent background (smaller than 100KB) from /static/nutstash.svg
* [ ] change logo url in /src/comp/elements/Logo.svelte

**Comment by BTCBap** [comment]
![Nutstash logo_transparentbg_85kb](https://user-images.githubusercontent.com/71675475/221580166-044e63a4-5f0b-4cf3-816f-630470904c64.png)

**Comment by gandlafbtc** [comment]
Thanks @BTCBap , the issue has already been completed by @Quin5 . Drop me your nostr and i zap you some sats as a token of appreciation
