### ISSUE TITLE
mint field not populated on token

### ISSUE THREAD

**Issue by gandlafbtc** [gandlafbtc/nutstash-wallet#37]
has been reported by npub1emj7ecmj2n03fl0gzz6yseg649gakh4tvmepvt0mtydh5hsgyzzqt5n4hs

needs investigation

**Comment by BilligsterUser** [comment]
[thread](https://snort.social/e/note1fjdh9l94r6xhalzr5pmr50lcd73gs4wquh6gw8fdydvv098dc0nqwnym5p)

**Comment by gandlafbtc** [comment]
at some point the protocol migrated from `mints :{ url, keysets }` to `mints :{ url, ids }` , before fixing this, it produced the same issue, maybe i didn't fix it completely

**Comment by gandlafbtc** [comment]
https://github.com/gandlafbtc/nutstash-wallet/pull/23

**Comment by gandlafbtc** [comment]
Hasn't come up since. maybe it was an out of date client issue
