### ISSUE TITLE
can´t pay Invoice

### ISSUE THREAD

**Issue by BilligsterUser** [gandlafbtc/nutstash-wallet#53]
![Screenshot - 06_03 002](https://user-images.githubusercontent.com/49797107/223235918-6d7c4a12-46a1-45bb-8f5a-c4efbefc1025.png)

![Screenshot - 06_03 003](https://user-images.githubusercontent.com/49797107/223235957-59a2b509-dba5-4ded-8bbc-8ca7d3911f06.png)

**Comment by gandlafbtc** [comment]
i think this has been fixed with #57
