### ISSUE TITLE
Allow undo when accidentally deleting mint.

### ISSUE THREAD

**Issue by mattsats** [gandlafbtc/nutstash-wallet#65]
I'm always frustrated when I accidentally click delete mint.

**Solution**
display an undo button right after removing mint url to add the mint back incase someone is exploring the app and accidentally deleted it.

I will be happy to tackle this issue myself, but I am a pleb dev and will need guidance.

**Comment by gandlafbtc** [comment]
We could also switch this around and add a pop up dialog asking for confirmation. Would probably be easier t implement and also better UX in my opinion.

**Comment by mattsats** [comment]
Sounds good! Asking for confirmation seems like the right way to go.

**Comment by gandlafbtc** [comment]
If you want, you can implement it! you can get some inspiration from the delete history button, there we have a pop up for confirming deletion.

https://github.com/gandlafbtc/nutstash-wallet/blob/main/src/comp/elements/ResetHistoryButton.svelte

Let me know if you need some more guidance! 

you can also join our dev group on telegram :  https://t.me/+DRy-rSe5wQtlYTk1

**Comment by mattsats** [comment]
Great thanks!

**Comment by gandlafbtc** [comment]
I re opened the issue, we can close it after we have a working implementation. Feel free to work on it and ask me for help if you need any.

**Comment by gandlafbtc** [comment]
I'll implement it :P
