### ISSUE TITLE
Multiple tabs on the same browser cause indefinite reload

### ISSUE THREAD

**Issue by Dayvvo** [gandlafbtc/nutstash-wallet#95]
**Describe the bug**
When I open the nutstash wallet app on more than one tab in the same browser. Both of them seem to be reloading indefinitely

**To Reproduce**

1. Go to 'https://wallet.nutstash.app'
2. Switch to the mints tab
3. Add the test mint as your first mint (https://testnut.cashu.space)
4. Both tabs keep reloading indefinitely

- OS: [MacOS 14]
- Browser [chrome, brave browser]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gandlafbtc** [comment]
Nutstash makes use of browser storage. There is no feature of synchronizing states across multiple instances, and it is discouraged to use it in more than one tab at a time

In #102 it will instead show a prompt to close the window, if more than one instance is open
