### ISSUE TITLE
Restore from seed Use a bip32/bip39 seed phrase to create recoverable ecash

### ISSUE THREAD

**Issue by GitKalle** [gandlafbtc/nutstash-wallet#96]
I can't find the feature "**Restore from seed** Use a bip32/bip39 seed phrase to create recoverable ecash." in the app what's described on your Hompage [Nutstash.app](https://nutstash.app/) at chapter [Stashing Features](https://nutstash.app/#fea).

Can you help me?

**Comment by gandlafbtc** [comment]
feature is only available in the v2 alpha version. It will also be released in the v2 stable version
