### ISSUE TITLE
View "send screen" while a tx is pending

### ISSUE THREAD

**Issue by dani69654** [gandlafbtc/nutstash-wallet#98]
Currently it does not seem to be possible to see the details of a pending send request, which mean that if the user does not copy the token from the send screen he cannot see it anymore.

I am willing to work on this, seems a great first task for me. Can it be useful to the project?

**Comment by gandlafbtc** [comment]
The tokens themselves will be in the pending tokens under the ecash tab.

But I agree, the UX is not the best. If you can come up with something more userfriendly I am happy to integrate it into nutstash :)

**Comment by gandlafbtc** [comment]
will be fixed in #102
