### ISSUE TITLE
Wrong type on mint request

### ISSUE THREAD

**Issue by lescuer97** [gandlafbtc/nutstash-wallet#99]
**Describe the bug**
Requesting for minting using bolt11 asks for the amount in string "1000" instead of being and integer 1000

**To Reproduce**

1. Go to dev.nutstash.app
2. Request minting new tokens with lightning 
3. Watch the call on networking devtools
4. See amount as string in call endpoint `v1/mint/quote/bolt11`

**Expected behavior**
Amount should be an int

**Screenshots**
![image](https://github.com/gandlafbtc/nutstash-wallet/assets/47948594/adea1f4e-32fe-4953-a4c9-829b867376e8)

**Desktop (please complete the following information):**

- OS: Linux
- Browser Chromium

**Additional context**

**Comment by gandlafbtc** [comment]
fixed in #102
